ansible/roles/basics/tasks/main.yml
This PR adds the OS-level package 'python3-jsonpatch' to the list of RPM packages to be installed on the target KVM host.
Fixes: #14
=> Added OS-level package python3-jsonpatch

.gitattributes
Resolves #24 
This PR updates the repo's .gitattribute file to allow GH to detect Markdown documents properly.
=> Proper detection of Markdown documents

ansible/roles/basics/tasks/main.yml, ansible/roles/ocp_install_clients/tasks/main.yml
Resolves #27
This PR adds installation of bash autocompletion scripts for OpenShift client tooling to the existing playbooks.
=> Added OpenShift command line tooling autocompletion for bash

ansible/roles/networking/tasks/main.yml, ansible/roles/ocp_cleanup/tasks/main.yml, ansible/roles/ocp_install_clients/tasks/main.yml, ansible/roles/ocp_install_cluster_wrapup/tasks/main.yml
Resolves #29 
This PR changes the way the playbooks handle the httpd service. While the service is required by the actual OCP installation (for caching RHCOS images locally) it's enablement state requires unchanged - if the httpd service is disabled at host reboot it will remain so.
After the OCP installation is finished the httpd service is stopped. 
=> Changed handling of httpd service

ansible/roles/basics/tasks/main.yml, ansible/roles/ocp_build_installer/tasks/main.yml
Resolves #36 
This PR ensures that the compilation of binaries via go is done in an isolated way using a dedicated GOPATH environment variable.
=> Isolated go compilation environments

ansible/roles/basics/tasks/main.yml, ansible/roles/ocp_build_installer/tasks/main.yml
Resolves #38 
This PR contains a fix for the prerequisite binary builds using 'go'. The go executable is now included in the corresponding PATH variable.
=> Included go binary location in PATH variable

.ansible-lint, ansible/roles/basics/defaults/main.yml, ansible/roles/basics/tasks/main.yml
Resolves #43 
This PR adds installing 'butane' to the playbooks. butane is compiled from source code before installation.
=> Add butane installation

ansible/roles/sanity_check/tasks/main.yml
Resolves #12 
This PR adds a sanity check that is run prior to installing OCP that ensure the correct version of libvirt to be present on the KVM host.
=> Added sanity check for incompatible libvirt packages

ansible/roles/basics/tasks/main.yml, ansible/roles/sanity_check/tasks/main.yml
Resolves #12 
The PR revises the workaround for the known incompatible libvirt version.
=> Twofold check for incompatible libvirt package

ansible/roles/networking/tasks/main.yml, ansible/roles/networking/templates/dnsmasq.openshift.conf.j2
Resolves #48 
This PR uses a template file for the NetworkManager dnsmasq configuration instead of augmenting an existing file with additional settings.
=> Use template file for NetworkManager dnsmasq configuration

ansible/filter_plugins/FilterUtils.py, ansible/roles/ocp_build_installer/tasks/main.yml
Resolves #50 
This PR introduces automatic detection of the OpenShift installer version that is to be used for installing the given OCP release. If the appropriate OpenShift installer version cannot be detected, it falls back to the default 'release-4.9'.
=> Added automatic detection of appropriate openshift-install version

ansible/roles/networking/tasks/main.yml, ansible/roles/ocp_cleanup/tasks/main.yml
Resolves #53 
This PR implements changes to prevent the /etc/resolv.conf file from accidentally being overwritten.
=> Prevent overwrite of /etc/resolv.conf backup file

ansible/check_ocp_cluster_state.yml, ansible/cleanup_ocp_install.yml, ansible/enable_crypto_resources.yml, ansible/group_vars/all.yml, ansible/group_vars/ppc64le_kvm_host.yml, ansible/group_vars/s390x_kvm_host.yml, ansible/group_vars/x86_64_kvm_host.yml, ansible/host_vars/host.yml.template, ansible/inventory.template, ansible/prepare_ocp_install.yml, ansible/reboot_host.yml, ansible/roles/basics/tasks/main.yml, ansible/roles/crypto/tasks/sanity_checks.yml, ansible/roles/firewall/tasks/main.yml, ansible/roles/networking/tasks/main.yml, ansible/roles/ocp_build_installer/tasks/main.yml, ansible/roles/ocp_cleanup/tasks/main.yml, ansible/roles/ocp_install_clients/tasks/main.yml, ansible/roles/ocp_install_cluster/tasks/main.yml, ansible/roles/ocp_install_cluster/templates/install-config.yaml.j2, ansible/roles/sanity_check/tasks/main.yml, ansible/roles/vbmc/tasks/main.yml, ansible/run_ocp_install.yml, ansible/run_sanity_checks.yml, ansible/setup_host.yml, ansible/start_ocp_cluster_nodes.yml, ansible/test_plugins/TestUtils.py, ansible/tune_ocp_install.yml
Resolves #35
This PR implements playbook changes to allow support for multiple KVM host architectures: s390x, ppc64le, x86_64.
Up until now the playbooks only supported s390x (which still remains the primary target platform and the only one in focus for further development of these playbooks).
Testing has been done on servers for all three supported architectures:
- s390x: IBM z14 LPAR, RHEL 8.4 and RHEL 8.5
- x86_64: Intel Xeon Platinum 8260 bare metal, RHEL 8.5
- ppc64le: IBM Power System LC922 bare metal, RHEL 8.5
=> Support for multiple server architectures: s390x, ppc64le, x86_64

ansible/group_vars/ppc64le_kvm_host.yml, ansible/group_vars/s390x_kvm_host.yml, ansible/group_vars/x86_64_kvm_host.yml, ansible/roles/sanity_check/tasks/main.yml
Resolves #59 
This PR introduces architecture-specific CPU overcommit factors for the built-in sanity checks.
=> Using architecture-dependent CPU overcommit factor for sanity checks

ansible/host_vars/host.yml.template, ansible/roles/ocp_build_installer/defaults/main.yml
Resolves #64 
This PR bumps the OCP version in the included host configuration template file to version 4.10.
=> Bumped OCP version

ansible/roles/basics/defaults/main.yml, ansible/roles/basics/tasks/main.yml, ansible/roles/ocp_cleanup/defaults/main.yml, ansible/roles/ocp_cleanup/tasks/archive_cluster_ocm.yml, ansible/roles/ocp_cleanup/tasks/main.yml, ansible/secrets/README.md, ansible/tasks/get_cluster_uid.yml, docs/DOCUMENTATION.md, docs/FAQ.md
Resolves #66
This PR adds integration with OCM so that upon cluster deletion the cluster subscription info in OCM is updated.
=> Added OCM integration for cluster deletion during cleanup

ansible/group_vars/all.yml, ansible/host_vars/host.yml.template, ansible/roles/ocp_install_cluster/templates/install-config.yaml.j2
Resolves #68 
This PR makes the internal OpenShift network type configurable by adding the host-specific configuration value `openshift_network_type`. The default network type is `OpenShiftSDN` (as previously) but can be overridden by the user.
=> Allow internet network type override

ansible/group_vars/all.yml, ansible/roles/basics/defaults/main.yml
Resolves #70
This PR contains version updates for some 3rd-party packages as well as an update to the default OpenShift cluster network type.
=> Bumped package versions, changed OCP network type default

ansible/group_vars/all.yml, ansible/host_files/.gitignore, ansible/host_files/README.md, ansible/host_vars/host.yml.template, ansible/roles/ocp_install_cluster/tasks/copy_advanced_configuration_files.yml, ansible/roles/ocp_install_cluster/tasks/main.yml, docs/DOCUMENTATION.md
Resolves #72 
This PR adds the ability for users to supply advanced cluster configuration files that are used by the OpenShift installer to tweak different aspects of the cluster installation process and the resulting cluster itself, in particular for the cluster network settings.
=> Added advanced cluster configuration capabilities

ansible/host_vars/host.yml.template, ansible/roles/ocp_build_installer/tasks/main.yml, ansible/roles/ocp_build_installer/tasks/patch_installer.yml, docs/DOCUMENTATION.md
Resolves #76 
This PR adds a new per-host configuration setting that allows to define a custom cluster network MTU size for the new OpenShift cluster to be installed.
=> Allow custom network MTU size

Dockerfile
Resolves #82 
This PR bumps the base image in Dockerfile to Python 3.9.
=> Bumped base image to Python 3.9

ansible/roles/basics/tasks/main.yml, ansible/roles/crypto/README.md, ansible/roles/sanity_check/tasks/main.yml, docs/DOCUMENTATION.md
Resolves #84 
This PR ensures that the playbooks only support target hosts running at least RHEL 8.6. This change was mandated by updated Python3 prerequites and their dependency on rust 1.56 (which is not available on older RHEL 8 releases).
=> Ensure target host is running at least RHEL 8.6

ansible/roles/basics/tasks/main.yml
Resolves #87 
This PR locks the versions of all Python3 packages installed via pip.
=> Install Python3 packages in two steps, lock down package versions

.ansible-lint, ansible/roles/basics/defaults/main.yml, ansible/roles/basics/tasks/main.yml, ansible/roles/crypto/files/cex-plugin-daemonset.yaml, ansible/roles/networking/tasks/main.yml, ansible/roles/ocp_cleanup/tasks/main.yml, ansible/roles/ocp_install_cluster/files/03_openshift-machineconfigpool_infra-0.yaml, ansible/roles/ocp_install_cluster/tasks/main.yml, ansible/roles/ocp_install_cluster/tasks/update_master_configuration.yml, ansible/roles/ocp_install_cluster_wrapup/tasks/persist_ssh_config.yml, ansible/roles/sanity_check/tasks/main.yml, ansible/roles/tuning/files/50-enable-rfs.yaml, ansible/roles/tuning/files/thp-workers-profile.yaml, ansible/roles/tuning/tasks/main.yml, ansible/tasks/check_cluster_state.yml, ansible/tasks/get_resolv_conf_location.yml, docs/DOCUMENTATION.md
Resolves #90 
This PR enables the use of Fedora 36 as host OS for the target KVM host. It also fixes Ansible linter violations that were introduced with the latest version of 'ansible-lint'.
=> Added Feora36 support and Ansible linter fixes

ansible/host_vars/host.yml.template, ansible/roles/ocp_install_cluster/templates/install-config.yaml.j2, ansible/run_ocp_install.yml, docs/DOCUMENTATION.md
Resolves #94 
This PR enables support for installing OCP in FIPS mode.
=> Enabled FIPS mode support

ansible/secrets/README.md
Resolves #100 
This PR fixes a typo in the playbook documentation which referred to the OCP pull secret file with an incorrect name.
=> Fixed typo

ansible/roles/ocp_build_installer/tasks/patch_installer.yml
Resolves #104 
This PR attempts to handle OCP installation that aren't able to handle custom MTU sizes as reported in issue #104
=> Add warning if custom MTU size is unsupported

ansible/roles/basics/tasks/main.yml
Resolves #112 
This PR turns off swap for Fedora OSs running on the target KVM host.
=> Haubenr disable swap fedora

ansible/roles/networking/tasks/main.yml, ansible/roles/networking/templates/haproxy.cfg.j2, ansible/roles/ocp_install_cluster/tasks/main.yml, ansible/roles/ocp_install_cluster/templates/install-config.yaml.j2, ansible/roles/ocp_install_cluster/templates/libvirt_network_dns_xml.j2, ansible/roles/soundness_check/tasks/main.yml, ansible/roles/tuning/tasks/k8s_configure_dfltcc.yml, docs/FAQ.md
Resolves #116
This PR adds support for single-node OpenShift (SNO) cluster installations.
Provide a concise description of the changes you want to merge with this pull request.
=> Haubenr support single node clusters

ansible/host_files/README.md, ansible/reboot_host.yml
Resolves #118 
This PR implements a way for the playbook user to include host-specific post-boot customization Ansible tasks without having to modify the source of any of the existing playbooks.
=> Implemented host-specific post-boot hook

ansible/roles/basics/defaults/main.yml, ansible/roles/basics/meta/main.yml, ansible/roles/common/meta/main.yml, ansible/roles/crypto/meta/main.yml, ansible/roles/firewall/meta/main.yml, ansible/roles/libvirt/meta/main.yml, ansible/roles/libvirt/tasks/main.yml, ansible/roles/networking/meta/main.yml, ansible/roles/ocp_build_installer/meta/main.yml, ansible/roles/ocp_cleanup/meta/main.yml, ansible/roles/ocp_install_clients/meta/main.yml, ansible/roles/ocp_install_cluster/meta/main.yml, ansible/roles/ocp_install_cluster_wrapup/meta/main.yml, ansible/roles/ocp_prepare_install/meta/main.yml, ansible/roles/ocp_provision_nodes/meta/main.yml, ansible/roles/selinux/meta/main.yml, ansible/roles/soundness_check/meta/main.yml, ansible/roles/soundness_check/tasks/main.yml, ansible/roles/tuning/meta/main.yml, ansible/roles/vbmc/meta/main.yml, docs/DOCUMENTATION.md
Resolves #128 
This PR adds Fedora 37 OS support for the target KVM host. It also adds support for libvirt-nss.
=> Added Fedora 37 host OS support, add libvirt-nss support

ansible/roles/libvirt/tasks/main.yml
Resolves #130
This PR fixes the libvirt-nss module configuration issue for RHEL operating systems.
=> Fixed libvirt-nss module configuration activation

ansible/roles/basics/defaults/main.yml, ansible/roles/soundness_check/tasks/main.yml, docs/DOCUMENTATION.md
Resolves #147 
This PR adds support for RHEL 8.8, RHEL 9.2 and Fedora 38 as KVM host OSes. Also the version of 3rd-party dependencies like go, yq etc. is bumped.
=> Added DCO signoff

ansible/roles/basics/defaults/main.yml, ansible/roles/ocp_cleanup/defaults/main.yml
Resolves #152
This PR fixes the reported OCM error as well as bumps to installed go version in preparation for OCP 4.14.
=> Fix OCM error, bump go version

ansible/roles/basics/defaults/main.yml
Resolves #.
ODF installation on KVM results in error on the go version.
```
TASK [ocp_build_installer : build openshift-install binary] ********************
fatal: [m13lp81]: FAILED! => changed=true 
ansible_job_id: j561153045517.132308
cmd:
- hack/build.sh
delta: '0:00:00.022213'
end: '2024-07-23 15:48:23.786460'
finished: 1
msg: non-zero return code
rc: 1
results_file: /tmp/.ansible_async/j561153045517.132308
start: '2024-07-23 15:48:23.764247'
started: 1
stderr: |-
++ dirname hack/build.sh
+ . hack/build-cluster-api.sh
++ set -e
+++ go env GOOS
+++ go env GOARCH
++ TARGET_OS_ARCH=linux_s390x
++ CLUSTER_API_BIN_DIR=/tmp/ansible.9_74xzt2ocpinst/installer/cluster-api/bin/linux_s390x
++ CLUSTER_API_MIRROR_DIR=/tmp/ansible.9_74xzt2ocpinst/installer/pkg/clusterapi/mirror/
++ …
```
=> ODF 4.16 requires a minimum go version 1.21
