ibm-s390-cloud/ocp-kvm-ipi-automation

ansible/roles/basics/tasks/main.yml
ansible/roles/crypto/README.md
ansible/roles/crypto/tasks/main.yml
ansible/roles/crypto/tasks/sanity_checks.yml
ansible/roles/ocp_cleanup/tasks/main.yml
ansible/roles/ocp_install_clients/tasks/main.yml
ansible/roles/ocp_install_cluster/templates/install-config.yaml.j2
ansible/roles/tuning/README.md
ansible/roles/tuning/tasks/main.yml

The PR contains a cleanup of minor inconsistencies in the playbooks and the accompanying documentation.
Fixes #3

Minor cleanup of inconsistencies

---

.gitattributes
.github/dco.yml
README.md

This PR introduces the following changes:
- adds DCO bot integration for the repository
- adds proper detection of YAML and Jinja templates as source files
- minor documentation change

Added workflow improvements

---

README.md
ansible/roles/basics/tasks/main.yml
ansible/roles/ocp_install_clients/tasks/download_client_tarballs.yml
ansible/roles/ocp_prepare_install/tasks/main.yml
ansible/roles/sanity_check/tasks/main.yml

The PR contains playbooks improvements, small fixes and documentation updates.
Fixes #10

Playbook improvements, documentation updates, small fixes

---

docs/DOCUMENTATION.md

Resolves #18 
This changeset fixes the relative links to other documentation files included in this repository.

Fix relative links

---

ansible/cleanup_ocp_install.yml
ansible/enable_crypto_resources.yml
ansible/prepare_ocp_install.yml
ansible/roles/sanity_check/tasks/main.yml
ansible/setup_host.yml
ansible/tune_ocp_install.yml

Resolves #12 
This PR changes the waythe lbvirt version sanity check is called by different playbooks.

Changed libvirt version sanity check

---

README.md
ansible/roles/libvirt/tasks/main.yml
docs/DOCUMENTATION.md

Resolves #35
This PR contains mostly documentation updates.

Documentation updates, minor fixes

---

docs/DOCUMENTATION.md
docs/FAQ.md

- clarified the Ansible workstation requirement part

Documentation updates

---

ansible/roles/basics/defaults/main.yml
ansible/roles/basics/tasks/main.yml

Resolves #79 
This PR fixes the Python3 package installation issues.

Upgrade pip and other essential Python packages

---

ansible/tasks/get_cluster_uid.yml

Resolves #96 
This PR attempts to fix the error described in the corresponding issue.

Added error handler

---

ansible/roles/basics/defaults/main.yml

Resolves #102
This PR bumps go to 1.18.7 to address issue #102 

Bumped go version

---

ansible/roles/basics/defaults/main.yml
ansible/roles/crypto/tasks/attach_mediated_device_to_domain.yml
ansible/roles/crypto/tasks/main.yml
ansible/roles/crypto/tasks/sanity_checks.yml
ansible/roles/ocp_cleanup/tasks/archive_cluster_ocm.yml
ansible/roles/ocp_cleanup/tasks/main.yml
ansible/roles/ocp_install_clients/tasks/download_client_tarballs.yml
ansible/roles/ocp_install_clients/tasks/main.yml
ansible/roles/ocp_install_cluster/tasks/setup_infra_cluster_nodes.yml
ansible/roles/ocp_install_cluster_wrapup/tasks/persist_ssh_config.yml
ansible/roles/ocp_install_cluster_wrapup/templates/ssh-config.j2
ansible/roles/sanity_check/tasks/main.yml
ansible/roles/tuning/tasks/k8s_disable_thps.yml
ansible/roles/tuning/tasks/k8s_enable_rfs.yml
ansible/roles/tuning/tasks/main.yml
ansible/roles/vbmc/tasks/main.yml
ansible/tasks/check_cluster_state.yml
ansible/tasks/get_resolv_conf_location.yml
docs/DOCUMENTATION.md
docs/FAQ.md
tekton/pipelines/deploy-ocp-kvm-host.yaml
tekton/pipelines/tune-ocp-kvm-host.yaml

Resolves #106
This PR addresses the issue described in #106 and adds documentation updates as well as a significant simplification of the Python package installation process

Documentation updates, Python package installation simplification and more

---

ansible/roles/basics/defaults/main.yml
ansible/roles/soundness_check/tasks/main.yml
docs/DOCUMENTATION.md

Resolves #110
This PR adds support for RHEL 8.7 and RHEL 9.1 as KVM target host OS.

Added support for RHEL 8.7 and RHEL 9.1

---

ansible/provision_ocp_infra_nodes.yml
ansible/provision_ocp_worker_nodes.yml
ansible/roles/ocp_provision_nodes/tasks/main.yml
docs/DOCUMENTATION.md

Resolves #122 
This PR removes the limitation described in the linked issue.

Haubenr allow addl worker nodes with existing infra nodes

---

ansible/roles/basics/tasks/install_terraform_providers.yml
ansible/roles/basics/tasks/main.yml
ansible/roles/ocp_build_installer/tasks/main.yml

This PR reduces the duration of the git clone tasks in the various playbooks.

Reduce duration of git clone tasks

---

ansible/roles/basics/tasks/main.yml
ansible/roles/firewall/tasks/main.yml
ansible/roles/ocp_cleanup/tasks/main.yml
ansible/roles/ocp_install_cluster/tasks/main.yml

This PR addresses some code linting issues introduced with the latest version of ansible-lint.

Addressed linter violations

---

ansible/roles/libvirt/tasks/main.yml

Resolves #133 
This PR addresses the issue reported in #133 by checking if authselect is present and enabled prior to making changes to /etc/nsswitch.conf

Check authselect configuration

---

ansible/host_files/README.md
ansible/host_vars/host.yml.template
ansible/roles/ocp_install_cluster/templates/install-config.yaml.j2
ansible/run_ocp_install.yml
ansible/tasks/check_cluster_state.yml
docs/FAQ.md

Resolves #136 
This PR includes a few minor QOL and usability updates.

Updated host configuration template file

---

ansible/ansible.cfg
ansible/roles/basics/tasks/install_terraform_providers.yml
ansible/roles/basics/tasks/main.yml
ansible/roles/ocp_build_installer/tasks/main.yml
ansible/roles/ocp_cleanup/tasks/archive_cluster_ocm.yml

Resolves #143 
This PR addresses the issue mentioned above. Also, it addresses a backward-compatibility issue with older Ansible versions (<= 2.14.0).

Go build fix

---

README.md
ansible/host_files/README.md
ansible/roles/tuning/files/thp-workers-profile.yml
docs/DOCUMENTATION.md

Resolves #145
This PR updates all references to IBM Z to reflect the latest IBM Z brand name changes.

Updated IBM Z branding

---

ansible/roles/networking/tasks/main.yml
ansible/roles/ocp_install_cluster/templates/libvirt_network_dns_xml.j2
ansible/roles/ocp_provision_nodes/files/imageregistry-cluster.yaml
ansible/roles/ocp_provision_nodes/tasks/main.yml

Resolves #149 
This PR fixes the haproxy configuration issue that occurs when additional worker / infrastructure nodes are being provisioned via the respective playbooks.

Fixed haproxy configuration issue for additional worker / infrastructure nodes
